# proxypool remote server url. Blank for http://127.0.0.1:8080
server_url: https://example.proxypoolserver.com
# server_url: https://example.proxypoolserver.com/clash/proxies?type=vmess


# For your local server
request: http   # http / https
domain:         # default: 127.0.0.1
port:           # default: 80

cron_interval: 15       # default: 15  minutes
show_remote_speed: true # default false

healthcheck_timeout:    # default 5
healthcheck_connection: # default 100

speedtest:              # default false
speed_connection:       # default 5
speed_timeout:          # default 10
